// <auto-generated/>
using System.Web.Mvc;
using MedicationsShortagesDashboard.Utilities;

namespace MedicationsShortagesDashboard.Controllers
{
    public class HomeController : BaseController
    {

    }
}
