// <auto-generated/>
using System.Web.Mvc;
using MedicationsShortagesDashboard.Services;

namespace MedicationsShortagesDashboard.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            this.ViewData["Username"] = Authentication.Username;
            this.ViewData["PageTitle"] = "Home";
            return this.View();
        }
    }
}
